title: "Cippo95's Blog"
email: cippo1995@gmail.com
github_username:  Cippo95 # DO NOT include the @ character, or else the build will fail!
show_excerpts: false # set to false to remove excerpts on the homepage
theme: minima
